name: template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.6
  get_it: ^7.2.0
  go_router: ^3.0.7
  injectable: ^1.5.3

dev_dependencies:
  build_runner: ^2.1.10
  dart_code_metrics: ^4.14.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  injectable_generator: ^1.5.3
  mocktail: ^0.0.1-dev.12

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  output_dir: lib/l10n/generated
